site_name: Veres One
theme:
  name: 'material'
  custom_dir: veresone_theme
pages:
    - 'Home': 'index.md'
    - 'Summary': 'summary.md'
    - 'Why Veres One?': 'why.md'
    - 'Credentials': 'credentials.md'
    - 'Sectors': 'sectors.md'
    - 'The Network':
        - 'Intro': 'network/index.md'
        - 'Nodes': 'network/nodes.md'
        - 'Accelerators': 'network/accelerators.md'
        - 'The Maintainer': 'network/maintainer.md'
        - 'The Board of Governors': 'network/governors.md'
        - 'Governance': 'network/governance.md'
        - 'Economic Model': 'network/economics.md'
        - 'Fees': 'network/fees.md'
    - 'Developers':
        - 'Intro': 'developers/index.md'
        - 'Quickstart': 'developers/quickstart.md'
#        - 'Guides': 'developers/guides.md'
#        - 'REST API': 'developers/rest-api.md'
    - 'FAQ': 'faq.md'
    - 'Agreements':
        - 'Intro': 'agreements/index.md'
        - 'Governor Agreement': 'agreements/governor.md'
        - 'Maintainer Agreement': 'agreements/maintainer.md'
        - 'Accelerator Agreement': 'agreements/accelerator.md'
        - 'Software License': 'agreements/software.md'
    - 'About': 'about.md'
