site_name: Veres One
site_url: https://docs.veres.one/
extra_css:
    - css/extra.css
theme:
  name: 'material'
  custom_dir: veresone_theme
  logo: img/logo-white-24px.png
  extra_css: 'foooooo'
pages:
    - 'Home': 'index.md'
    - 'Summary': 'summary.md'
    - 'Why Veres One?': 'why.md'
    - 'Credentials': 'credentials.md'
    - 'Sectors': 'sectors.md'
    - 'The Network':
        - 'Intro': 'network/index.md'
        - 'Nodes': 'network/nodes.md'
        - 'Accelerators': 'network/accelerators.md'
        - 'The Maintainer': 'network/maintainer.md'
        - 'The Board of Governors': 'network/governors.md'
        - 'Governance': 'network/governance.md'
        - 'Economic Model': 'network/economics.md'
        - 'Funding': 'network/funding.md'
    - 'Developers':
        - 'Intro': 'developers/index.md'
        - 'Quickstart': 'developers/quickstart.md'
#        - 'Guides': 'developers/guides.md'
#        - 'REST API': 'developers/rest-api.md'
    - 'FAQ': 'faq.md'
    - 'Agreements':
        - 'Intro': 'agreements/index.md'
        - 'Governor Agreement': 'agreements/governor.md'
        - 'Maintainer Agreement': 'agreements/maintainer.md'
        - 'Accelerator Agreement': 'agreements/accelerator.md'
        - 'Software License': 'agreements/software.md'
        - 'Individual Contributor Agreement': 'agreements/icla.md'
        - 'Corporate Contributor Agreement': 'agreements/ccla.md'
    - 'About': 'about.md'
